clubWebsite/routes.py
import time
import secrets
import html
import urllib
import html
from werkzeug import unescape

import traceback
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail

from flask import Blueprint, render_template, send_from_directory, request, redirect, url_for, abort, Response, flash

from clubWebsite.forms import RegistrationForm
from clubWebsite.database.models import Member
from clubWebsite.config import BaseConfig

views_blueprint = Blueprint('views', __name__, template_folder='templates')

@views_blueprint.route("/")
def index():
    return render_template("index.html")
 

@views_blueprint.route("/hack")
def hack():
    return render_template("hack.html")

@views_blueprint.route("/about")
def about():
    return render_template("about.html")


@views_blueprint.route("/calendar")
def calendar():
    return render_template("calendar.html")

@views_blueprint.route("/hackathon")
def hackathon():
    return render_template("hackathon.html")

@views_blueprint.route("/hackathon_apply")
def hackathon_apply():
    return render_template("apply.html")

@views_blueprint.route("/join", methods=['GET','POST'])
def join():
    # Initialize form and check if it is valid
    form = RegistrationForm(meta={'csrf':False})
    valid = form.validate_on_submit()

    # On form submission with valid input
    if request.method == 'POST' and valid:
        confirmation_token, confirmation_time = Member.generate_confirmation_token()
        confirmation_link = request.url_root.rstrip('/') + url_for('views.confirm', confirmation_token=confirmation_token)

        html_content = 'Hi ' + html.escape(form.first_name.data) + ',<br><br>'
        html_content += 'You signed up for the Enthusiastic Programmers club. Verify that the following information is correct:<br><ul>'
        html_content += '<li>First name: ' + html.escape(form.first_name.data) + '</li>'
        html_content += '<li>Last name: ' + html.escape(form.last_name.data) + '</li>'
        html_content += '<li>Student ID: ' + html.escape(form.student_id.data) + '</li>'
        html_content += '</ul>'
        html_content += 'If the above information is correct, click this link to confirm your membership: '
        html_content += '<a href="' + html.escape(confirmation_link) + '">' + html.escape(confirmation_link) + '</a><br>'

        html_content += '''
Otherwise, simply ignore this email and submit new information on the join page. If you have already clicked the confirmation link, that is OK. Your information will be updated when you re-confirm.<br><br>

If you did not initiate this action, ignore this email.'''

        message = Mail(
            from_email='no-reply@' + request.host,
            to_emails=form.email.data,
            subject='Club membership confirmation',
            html_content=html_content
        )

        try:
            key = BaseConfig.SENDGRID_API_KEY
            if key is None:
                print("Confirmation email for %s failed. Missing SENDGRID_API_KEY." % form.first_name.data)
                abort(500)
                abort(Response('Failed to send confirmation email. Please contact the website administration.'))
            sg = SendGridAPIClient(key)
            response = sg.send(message)
        except Exception as e:
            traceback.print_exc()
            abort(500)
            abort(Response('Failed to send confirmation email. Please try again later.'))



        Member.create(form.student_id.data, form.email.data, form.first_name.data, form.last_name.data, 
                      confirmation_token=confirmation_token, confirmation_time=confirmation_time)

        # Redirect to email_sent page
        return redirect(url_for('views.email_sent', email=form.email.data))
    
    # Render form template when method is GET, or form is not valid
    return render_template("join.html", form=form)

@views_blueprint.route("/email_sent")
def email_sent():
    email = request.args.get('email')
    if not email:
        abort(400)
        abort(Response('Missing email'))
    msg = 'An email has been sent to %s to confirm your membership. You might have to check your spam folder.' % email
    
    flash(msg)
    return render_template("base.html", title="Registered")

@views_blueprint.route("/confirm")
def confirm():
    token = request.args.get('confirmation_token')
    if not token:
        abort(400)
        abort(Response('Missing confirmation token'))

    member = Member.query.filter_by(confirmation_token=token).one_or_none()
    if not member:
        flash("Invalid or expired confirmation link. Please try again.")
        return render_template("base.html", title="Membership confirmation")

    status, message = member.confirm()

    flash(message)
    return render_template("base.html", title="Membership confirmation")

clubWebsite/templates/about.html
{% extends "base.html" %}
{% block main %}
<!-- HIDDEN SECRET MEMES-->
<!-- #{
<figure class="ethan-image">
    <h2 style="text-decoration:underline;">Do you know this man??!?</h2>
    <a href="{{url_for('views.about')}}">
        <img src="{{ url_for('static', filename='images/this-is-ethan.png') }}" alt="Our boi Ethan with some loot" style="width:450px"/>
    </a>
    <p class="basic-font" style="text-align:center;">Just take a look at that loot! WOW!</p>
    <p class="basic-font" style="text-align:center;font-size:32px">This is a man that knows what he likes</p>
    <p class="basic-font">Pictured above: The magic man coming back from a raid with hundreds of pounds of swag for his supporters.</p>
    <p></p>
</figure>

<div class="ethan-info">
    <p>
        <span style="font-size:28px">&nbsp;Ethan Bonavida</span> is the president of the Computer Science club here at Moorpark College.
        as the president of our very special club, Ethan has many jobs, including:
    </p>
    <ul>
            FA
        <li>Looking awesome</li>
        <li>Attracting the babez</li>
        <li>Charming faculty into increasing the club budget</li>
        <li>Bringing back prizes as the people's champion</li>
        <li style="text-decoration:line-through;font-size:10px;">Forcing club members to write websites for him</li>
    </ul>
    <p>
        &nbsp;&nbsp;Now I know what you're thinking here: there couldn't possibly be a man capable of doing all these things. 
        Well, you're right: Ethan is actually 1/36th part <span style="color: darkred">redwood</span>. I don't know how that works 
        either, but it means he's not <span style="font-style: oblique;">just</span> a man. We haven't noticed anything very redwood 
        about him, though.
    </p>
    <p>
        &nbsp;&nbsp;However, upon being elected president of the Enthusiastic Programmers club, the Bonafide Bonavida 
        gained the power of omniscience, which only increased the radiance of his awesome. Instead of having 50 times the 
        power level of a regular human, he now has an effectively infinite advantage over the average person. This makes 
        him even more capable of the job entrusted to him by the good club members of Enthusiastic Programmers.
    </p>
    <p>
        &nbsp;&nbsp;This hero is so well liked, that he often can't play his recent favorite game, Destiny 2, in peace and quiet 
        from his bothersome followers' questions and attention. The following is a graph showing the amount of disappointment 
        accrued from Ethan's dismissal:
    </p>
    <img src="{{ url_for('static', filename='images/graph-ethan-dismissal.png') }}" alt="Very disappointing numbers in exponential form" style="text-align:center;width:500px"/>
</div> 
#} -->



<h4>This is a page about us. Here are some quick FAQ's; hopefully it answers yours. Also meet the creators behind the programming and design of the whole website.</h4>
<div class="faq-block">
    <p class="question-text">Q: What is this website actually for?</p>
    <p class="answer-text">A: To showcase and inform others about Moorpark College's amazing clubs</p>           
</div>
<br/>
<div class="faq-block">
    <p class="question-text">Q: Do I need any computer science experience? </p>
    <p class="answer-text">A: Nope! Anyone is welcome to come by whether you have no experience or you're Elon Musk.</p>
</div>
<br/>
<div class="faq-block">
    <p class="question-text">Q: How can I join this club?</p>
    <p class="answer-text">A: There is no official way to join, as anyone is welcome in our club so just stop on by our meeting times posted on the calender. Feel free to try our Join page to get added to our mailing list. </p>
</div>
<br/>
<div class="faq-block">
    <p class="question-text">Q: How can I contact this club?</p>
    <p class="answer-text">A: Feel free to email us at EnthusiasticProgrammersClub@gmail.com</p>           
</div>
<!-- think about trying to add a recaptcha thing to unlock discord link?-->
<br/> 
<hr>
<br>
<div class="about-block">
        <p class="about-text">ENTHUSIASTIC PROGRAMMERS CLUB OFFICIALS</p>
        <p>Jesus "Anthony" Gutierez: President of Enthusiastic Programmers</p>
        <p>Chris Lowewnthal: Vice President Enthusiastic Programmers</p>
        <p>Arzhang Valadkhani: Secretary of Enthusiastic Programmers</p>
        <p>Zubair Sidhu: Treasurer of Enthusiastic Programmers</p>
        <p>Ethan Bonavida: Technical Advisor of Enthusiastic Programmers</p>
        <p>Ari Berkowicz: Activity Organizer of Enthusiastic Programmers</p>
    </div>
<br/> 
<hr>
<br/>
<div class="about-block">
    <p class="about-text">MEET THE TEAM</p>
    <p class="about-name">Ariel Berkowicz: Lead Organizer</p>
    <p><img src="{{ url_for('static', filename='images/ariel.png') }}"  style="width:130px"/></p> 
    <p class="about-name">Ethan Bonavida: President of Production and Design</p>
    <p><img src="{{ url_for('static', filename='images/this-is-ethan.png') }}"  style="width:175px"/></p> 
    <p class="about-name">Roger Fachini: Co-Lead Programmer and Designer</p>
    <p><img src="{{ url_for('static', filename='images/roger.jpg') }}"  style="width:155px"/></p> 
    <p class="about-name">James Taylor: Co-Lead Programmer and Designer</p>   
    <p><img src="{{ url_for('static', filename='images/james.jpg') }}"  style="width:140px"/></p> 
    <p class="about-name">Benjamin Hiebert: Senior Meme Engineer</p>
    <p><img src="{{ url_for('static', filename='images/ben.jpg') }}"  style="width:130px"/></p> 
</div>
<p class="cr"> &copy;2020 Enthusiastic Programmers </p>
{% endblock %}

clubWebsite/templates/apply.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            Hack the 805
        </title>

        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/apply.css') }}"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </head>
    <body>
        <header>

        </header>


        <main>
            <form class="questions">
                <div class="question">
                    <label>First name</label>
                    <input type="text" class="entry">
                </div>
                <div class="question">
                    <label>Last name</label>
                    <input type="text" class="entry">
                </div>
                <div class="question">
                    <label>Email</label>
                    <input type="email" class="entry">
                </div>
                <div class="question">
                    <label>Enter your age</label>
                    <input type="number" class="entry" min="18" max="150">
                </div>
                <div class="question">
                    <label>School</label>
                    <select class="entry" required>
                        <option value="">--Please choose a school--</option>
                        <option value="moorpark-college">Moorpark College</option>
                        <option value="ucla">UCLA</option>
                        <option value="usc">USC</option>
                        <option value="long-beach">CSU Long beach</option>
                        <option value="santa-cruz">UC Santa Cruz</option>
                        <option value="caltech">Caltech</option>
                    </select>
                </div>
                <div class="question">
                    <label>What is your t-shirt size?</label>
                    <select class="entry" required>
                        <option value="">--Please choose a size--</option>
                        <option value="small">Small</option>
                        <option value="medium">Medium</option>
                        <option value="large">Large</option>
                        <option value="xl">XL</option>
                        <option value="xxl">XXL</option>
                    </select>
                </div>
                <div class="question">
                    <label>Upload your resume</label>
                    <input type="file" class="entry">
                </div>
                <div class="question">
                    <label>Tell us about a project you made that you were most proud of. What made that project special to you?</label>
                    <input type="text" class="entry">
                </div>
                <div class="question">
                    <label>If Moorpark Community College was abbreviated into hackathon themes where M stood for Mobility and C stood for Collaboration what would College as a C stand for?</label>
                    <input type="text" class="entry">
                </div>
                <div class="question">
                    <label>Inform us of any needs/allergies you want to notify us about</label>
                    <input type="text" class="entry">
                </div>
                <div class="submit">
                    <input type="submit" value="Submit">
                </div>
            </form>

        </main>
    </body>
</html>

clubWebsite/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>
            {{ title if title else  "Enthusiastic Programmers"}}
        </title>
        <link href="{{ url_for('static', filename='images/favicon.ico') }}" type="image/x-icon" rel="icon">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='stylesheets/ep-base.css') }}"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <header>
            <a href="{{url_for('views.index')}}">
                <img src="{{ url_for('static', filename='images/EPFinal.png') }}" style="width:320px;"/>
            </a>
            <nav id="nav-bar">
                <ul>
                    <li class="{% if request.endpoint == 'views.index' %} current-page {% endif %}">
                        <a href="{{ url_for('views.index') }}">
                            Home
                        </a>
                    </li>
                    

                    <li class="{% if request.endpoint == 'views.hack' %} current-page {% endif %}">
                        <a href="{{ url_for('views.hack') }}">
                            Showcase
                        </a>
                    </li>

                     <li class="{% if request.endpoint == 'views.calendar' %} current-page {% endif %}">
                        <a href="{{ url_for('views.calendar') }}">
                            Calendar
                        </a>
                    </li> 
                    
                    <li class="{% if request.endpoint == 'views.about' %} current-page {% endif %}">
                        <a href="{{ url_for('views.about') }}">
                            About 
                        </a>
                    </li>

                    <li class="{% if request.endpoint == 'views.hackathon' %} current-page {% endif %}">
                        <a href="{{ url_for('views.hackathon') }}">
                            Hack-The-805
                        </a>
                    </li>

                    <!--<li class="{% if request.endpoint == 'views.join' %} current-page {% endif %}">
                        <a href="{{ url_for('views.join') }}">
                            Join
                        </a>
                    </li>-->
                </ul>
            </nav>
        </header>

        <main>
            {% with messages = get_flashed_messages() %} 
                {% if messages %} 
                    {% for message in messages %}
                        <div class="alert">
                            {{ message }}
                        </div>
                    {% endfor %} 
                {% endif %} 
            {% endwith %}

            {% block main %}

            {% endblock %}
        </main>
    </body>
</html>

clubWebsite/templates/calendar.html
{% extends "base.html" %}
{% block main %}



<div >
    <iframe src="https://calendar.google.com/calendar/b/2/embed?height=600&amp;wkst=1&amp;bgcolor=%230B8043&amp;ctz=America%2FLos_Angeles&amp;src=ZW50aHVzaWFzdGljcHJvZ3JhbW1lcnNjbHViQGdtYWlsLmNvbQ&amp;src=bHQ2ZTBjcmlsZWk4OWJ2OWZscWVjb2k4bmNAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ&amp;src=ZW4udXNhI2hvbGlkYXlAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&amp;color=%230B8043&amp;color=%23F6BF26&amp;color=%23D50000&amp;mode=WEEK&amp;title=Enthusiastic%20Programmers%20Club&amp;showPrint=0&amp;showTz=1&amp;showCalendars=1" style="border-width: 0px; padding-top: 15px; " width="1550" height="725" frameborder="0" scrolling="no"></iframe>
</div>
                    <p class="cr"> &copy;2020 Enthusiastic Programmers </p>
{% endblock %}

clubWebsite/templates/contact.html
<!DOCTYPE html>
<html>
    <head>
        <title>Ethansiastic Programmers Anonymous</title>
        <link rel="stylesheet" type="text/css" href="/static/stylesheets/ep-base.css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </head>
    <body>
        <header>
            <a href="{{url_for('views.index')}}"><img src="/static/images/enthusiastic-logo.png" style="width:320px;"/></a>
            <nav id="nav-bar">
                <ul>
                    <li><a href="{{url_for('views.index')}}">Home</a></li>
                    <li><a href="{{url_for('views.faq')}}">FAQ</a></li>
                    <li><a href="{{url_for('views.about')}}">About Ethan</a></li>
                    <li class="current-page"><a>Contact Info</a></li>
                    <li><a href="{{url_for('views.join')}}">Join Club</a></li>
                </ul>
            </nav>
        </header>

        <main>
            <p>Nothing here either... sorry to disappoint -\('.')/-</p>
        </main>
    </body>
</html>

clubWebsite/templates/hackathon.html
<!DOCTYPE html>
<html>

<head>
    <title>
        Hack the 805
    </title>
    <link rel="stylesheet" href="static/font-awesome/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="static/stylesheets/hackathon.css" />
    <link rel="stylesheet" type="text/css" href="static/stylesheets/navbar.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>

<body>
    <div class="fixed-top corona"><span>Due to COVID-19, Hack the 805 may be virtual or delayed</span></div>
    <header class="fixed-top">
        <a href="{{ url_for('views.index') }}">
            <img src="static/images/EPFinal_dark.png" class="logo" />
        </a>

        <nav class="navbar" id="nav-menu-container">
            <ul class=" ml-auto text-uppercase nav-menu">
                <li class="nav-item" role="presentation"><a class="nav-link js-scroll-trigger" href="#intro">Home</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link js-scroll-trigger" href="#about">About</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link js-scroll-trigger" href="#schedule">Schedule</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link js-scroll-trigger" href="#sponsors">Sponsors</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link js-scroll-trigger" href="#faq">FAQ</a></li>
                <li class="nav-item" role="presentation"><a class="nav-link js-scroll-trigger" href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <!-- uh what is this static error? not sure about it. -->
        <div id="intro" style="background-image: url('{{ url_for('static', filename='images/mountain.svg') }}');">
            <div class="intro-container">
                <h1>Hack the 805</h1>
                <p>Date TBD, Moorpark College</p>

                <a class="apply-button"">Apply</a>
            </div>
        </div>

        <section class="about-section section">
            <div class="about-cols">
                <div class="col1">
                    <h2 id="about" class="hash-link">About</h2>
                    <p>Moorpark College is hosting a Ventura County based hackathon for college students. For two days, students will team together and compete to push the boundaries of technology through hardware, software, and emerging disciplines such as machine learning. Hack805 wants to set the gold standard for community college hackathons.</p>
                </div>
                <div class="col2">
                    <h3>Where</h3>
                    <p>Moorpark College, Moorpark, CA</p>
                </div>
                <div class="col3">
                    <h3>When</h3>
                    <p>TBD</p>
                </div>
            </div>
        </section>

        <section class="schedule-section section centered-section">
            <div class="centered-header-container">
                <h2 id="schedule" class="hash-link">Schedule</h2>
            </div>
            <hr>
            <div class="schedule-boxes">
                <ol class="schedule-list schedule-box">                
                    <li class="time-header">
                        <h3>April 3</h3>
                        <!--<hr>--->
                    </li>
                    <li class="time-slot">
                        <time>04:00 PM</time>
                        <div class="schedule-event">Registration opens</div>
                    </li>
                    <li class="time-slot">
                        <time>06:00 PM</time>
                        <div class="schedule-event">Opening ceremony</div>
                    </li>
                    <li class="time-slot">
                        <time>07:00 PM</time>
                        <div class="schedule-event">Hacking begins</div>
                    </li>
                    <li class="time-slot">
                        <time>08:00 PM</time>
                        <div class="schedule-event">Dinner</div>
                    </li>
                    <li class="time-slot">
                        <time>09:00 PM - 10:00 PM</time>
                        <div class="schedule-event">Workshop 1</div>
                    </li>
                    <li class="time-slot">
                        <time>10:00 PM - 11:00 PM</time>
                        <div class="schedule-event">Workshop 2</div>
                    </li>
                    <li class="time-slot">
                        <time>11:00 PM - 12:00 AM</time>
                        <div class="schedule-event">Workshop 3</div>
                    </li>
                </ol>
                <ol class="schedule-list schedule-box">  
                    <li class="time-header">
                        <h3>April 4</h3>
                        <!--<hr>--->
                    </li>
                    <li class="time-slot">
                        <time>12:00 AM</time>
                        <div class="schedule-event">Midnight snack</div>
                    </li>
                    <li class="time-slot">
                        <time>2:00 AM</time>
                        <div class="schedule-event">Cup stacking</div>
                    </li>
                    <li class="time-slot">
                        <time>3:00 AM</time>
                        <div class="schedule-event">Fun event 2</div>
                    </li>
                    <li class="time-slot">
                        <time>07:00 AM</time>
                        <div class="schedule-event">Breakfast</div>
                    </li>
                    <li class="time-slot">
                        <time>08:00 AM - 09:00 AM</time>
                        <div class="schedule-event">Workshop 4</div>
                    </li>
                    <li class="time-slot">
                        <time>09:00 AM - 10:00 AM</time>
                        <div class="schedule-event">Workshop 5</div>
                    </li>
                    <li class="time-slot">
                        <time>11:00 AM - 12:00 PM</time>
                        <div class="schedule-event">Workshop 6</div>
                    </li>
                    <li class="time-slot">
                        <time>12:00 PM</time>
                        <div class="schedule-event">Lunch</div>
                    </li>
                    <li class="time-slot">
                        <time>3:00 PM</time>
                        <div class="schedule-event">Fun event 3</div>
                    </li>
                    <li class="time-slot">
                        <time>4:00 PM || 7:00 PM</time>
                        <div class="schedule-event">End hacking, dinner</div>
                    </li>
                    <li class="time-slot">
                        <time>5:00 PM || 8:00 PM</time>
                        <div class="schedule-event">Closing ceremony, winners, prizes</div>
                    </li>
                </ol>
            </div>
        </section>
        <section class="sponsors-section section centered-section">
            <div class="centered-header-container">
                <h2 id="sponsors" class="hash-link">Sponsors</h2>
            </div>
            <ul class="sponsors-list">
                <li><img src="{{ url_for('static', filename='images/sponsors/1.png') }}"></li>
                <li><img src="{{ url_for('static', filename='images/sponsors/2.png') }}"></li>
            </ul>
        </section>

        <section class="faq-section section centered-section">
            <div class="centered-header-container">
                <h2 id="faq" class="hash-link">FAQ</h2>
            </div>
            <ul class="faq-list">
                <li class="question-answer">
                    <div class="question">What is a hackathon?</div>
                    <div class="answer">A hackathon is a competition where teams compete to build either software or hardware projects. At the end of the competition, the projects will be demonstrated to judges who will award prizes to the winners based on categories such as best hardware hack, best use of a company's API, etc.</div>
                </li>
                <li class="question-answer">
                    <div class="question">Who can join?</div>
                    <div class="answer">Anyone can join so long as they are enrolled in a college.</div>
                </li>
                <li class="question-answer">
                    <div class="question">What do I bring?</div>
                    <div class="answer">Bring a laptop, a charger, a change of clothes, and toiletries.</div>
                </li>
                <li class="question-answer">
                    <div class="question">Are workshops mandatory?</div>
                    <div class="answer">No.</div>
                </li>
                <li class="question-answer">
                    <div class="question">How much coding experience do I need?</div>
                    <div class="answer">None! Hackathons are a great place to learn new skills from others or through workshops. Nevertheless, the more experience you bring, the more impressive your project will be.</div>
                </li>
            </ul>
        </section>

        <section class="contact-section section centered-section">
            <div class="centered-header-container">
                <h2 id="contact" class="hash-link">Contact</h2>
            </div>
            <p>Contact us at EnthusiasticProgrammersClub@gmail.com</p>
        </section>
    </main>

    <script src="static/jquery/jquery.min.js"></script>
    <script src="static/jquery/jquery-migrate.min.js"></script>


    <script src="static/easing/easing.min.js"></script>

    <script src="static/superfish/hoverIntent.js"></script>
    <script src="static/superfish/superfish.min.js"></script>

    <script src="static/wow/wow.min.js"></script>

    <script src="static/touchSwipe/jquery.touchSwipe.min.js"></script>

    <script src="static/js/hackathon.js"></script>
</body>

</html>

clubWebsite/templates/join.html
{% extends "base.html" %}
{% block main %}
<form id="join-club" action="{{url_for('views.join')}}" method="POST">
    {{ form.hidden_tag() }}
    <div>
        {{ form.first_name.label() }}
        {{ form.first_name() }}
        {% for error in form.first_name.errors %}
            <small style="color: red">
                {{ error }}
            </small> 
        {% endfor %}
    </div>
    <div>
        {{ form.last_name.label() }}
        {{ form.last_name() }}
        {% for error in form.last_name.errors %}
            <small style="color: red">
                {{ error }}
            </small> 
        {% endfor %}
    </div>
    <div>
        {{ form.student_id.label() }}
        {{ form.student_id() }}
        {% for error in form.student_id.errors %}
            <small style="color: red">
                {{ error }}
            </small> 
        {% endfor %}
    </div>
    <div>
        {{ form.email.label() }}
        {{ form.email() }}
        {% for error in form.email.errors %}
            <small style="color: red">
                {{ error }}
            </small> 
        {% endfor %}
    </div>
    {{ form.submit() }}
</form>

<p class="cr"> &copy;2020 Enthusiastic Programmers </p>
{% endblock %}

clubWebsite/templates/template.html
<!DOCTYPE html>
<html>
    <head>
        <title>{{title}}</title>
        <link href="/static/images/favicon.ico" type="image/x-icon" rel="icon">
        <link rel="stylesheet" type="text/css" href="/static/stylesheets/ep-base.css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
    </head>
    
    <body>
        <header>
            <a href="{{url_for('views.index')}}"><img src="/static/images/EPFinal.png" style="width:320px;"/></a>
            <nav id="nav-bar">
                <ul>
                    <li><a href="{{url_for('views.index')}}">Home</a></li>                    
                    <li><a href="{{url_for('views.about')}}">About</a></li>
                    <li><a href="{{url_for('views.hack')}}">Hackathons</a></li>
                    <li><a href="{{url_for('views.calendar')}}">Event Calendar</a></li>                    
                    <li><a href="{{url_for('views.join')}}">Join Club</a></li>
                </ul>
            </nav>
        </header>

        <main>
            {{main}}
        </main>
    </body>
</html>